solutions to task 0x11-python-network_1
